from typing import List

import yake
from rake_nltk import Rake
from app.models.llm_models import RAGResponse


def grouding_check(query : str, data : str):
    kw_extractor = yake.KeywordExtractor()
    
    keywords = kw_extractor.extract_keywords(query)
    
    keywords1 = []
    for phrase,_ in keywords:
        phrase = list(phrase.split(" "))
        for words in phrase:
            keywords1.append(words)
    
    score = 0
    
    total_size = len(keywords1)
    present = 0
    for words in keywords1:
        if words.lower() in data.lower():
            present += 1
    
    score = present / (total_size+1)
    return score

def process_llm_response(llm_response : RAGResponse):
    
    chunks = llm_response.chunk_retrieved
    chunk_text = ""
    print(f"Length of chunks retrieved is : {len(chunks)}")
    for chunk in chunks:
        chunk_text += chunk.text
        chunk_text += "\n"
    
    answer = llm_response.answer
    print(f"Answer generated by LLM is : {answer}")
    print(f"Chunk text is : {chunk_text}")
    return answer, chunk_text

def llm_grounding_check(llm_response : RAGResponse):
    answer, chunk_text = process_llm_response(llm_response)
    score = grouding_check(answer, chunk_text)
    print(f"Grounding score is : {score}")
    if score > 0.85:
        return True
    else:
        return False